version: "3.1"
services:
  prlmntq_etl_camara:
    build: .
    image: prlmntq_etl_camara
    container_name: prlmntq_etl_camara
    restart: always
    ports:
      - 8004:8004
    volumes:
      - .:/usr/src/etl_camara
    networks:
      - prlmntq_net

networks:
  prlmntq_net:
    external: true
